//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLTWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.SPtheoMaus = new HashSet<SPtheoMau>();
        }
    
        public string MaSanPham { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm.")]
        [Display(Name = "Tên sản phẩm")]
        public string TenSanPham { get; set; }
        public string MaPhanLoai { get; set; }
        public Nullable<long> GiaNhap { get; set; }

        [RegularExpression(@"^\d+(\.\d{0,2})?$", ErrorMessage = "Định dạng đơn giá không hợp lệ.")]
        public Nullable<long> DonGiaBanNhoNhat { get; set; }

        [RegularExpression(@"^\d+(\.\d{0,2})?$", ErrorMessage = "Định dạng đơn giá không hợp lệ.")]
        public Nullable<long> DonGiaBanLonNhat { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string MoTaNgan { get; set; }

        [RegularExpression(@"^.+\.jpg$", ErrorMessage = "Định dạng file ảnh không hợp lệ.")]
        public string AnhDaiDien { get; set; }
        public Nullable<bool> NoiBat { get; set; }
        public string MaPhanLoaiPhu { get; set; }
    
        public virtual PhanLoai PhanLoai { get; set; }
        public virtual PhanLoaiPhu PhanLoaiPhu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPtheoMau> SPtheoMaus { get; set; }
    }
}
